### ISSUE TITLE
RBM Server Issue (possibly a memory leak)

### ISSUE THREAD

**Issue by LunarExplorer233** [RainbowMiner/RainbowMiner#2630]
I am running a RBM server with around 200 client machines, and I frequently get this error (usually occurs every 6-12 hours) and I have to continuously start up my docker container because it keeps crashing.

An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
./start.sh: line 23:    13 Aborted                 (core dumped) pwsh -ExecutionPolicy bypass -Command ${command}

**Comment by RainbowMiner** [comment]
That is most def. a PowerShell bug. Could in fact be caused by an out of memory error. I'll contact the Powershell developers to clarify this issue.

**Comment by whitindllc** [comment]
its on the windoze side as well... rbm is eating a 1bg of memory 1 hour after start up....
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/72153870-94db-4cbc-9aff-5e8f1e1a50d8)

**Comment by whitindllc** [comment]
im on this 
![image](https://github.com/RainbowMiner/RainbowMiner/assets/128111946/35d876d9-7e1c-43e3-abf7-1769776aa9df)
